spring:
  application:
    name: ccshop-upload
  servlet:
    multipart:
      max-file-size: 5MB #限制文件上传的大小
server:
  port: 8082

#Eureka
eureka:
  client:
    service-url:
      defaultZone: http://121.196.169.60:10086/eureka
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
fdfs:
  so-timeout: 1501
  connect-timeout: 601
  thumb-image:             #缩略图生成参数
    width: 150
    height: 150
  tracker-list:            #TrackerList参数,支持多个
    - 121.196.169.60:22122
ccshop:
  upload:
    baseUrl: https://upload.hytree.link/
    allowTypes:
      - image/jpg
      - image/jpeg
      - image/png
      - image/bmp
